# Generated by Django 5.1.1 on 2024-09-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='No last name...', max_length=120),
        ),
    ]
